/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ssosnik.greencode.api;

import java.util.List;

import javax.annotation.Generated;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ssosnik.greencode.model.Clan;
import com.ssosnik.greencode.model.Players;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;

@Generated(value = "com.ssosnik.greencode.codegen.languages.SpringCodegen", date = "2023-04-01T16:14:58.930237600+02:00[Europe/Warsaw]")
@Validated
@Tag(name = "onlinegame", description = "the onlinegame API")
public interface OnlinegameApi {


    /**
     * POST /onlinegame/calculate
     * Calculate order
     *
     * @param players  (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "calculate",
        description = "Calculate order",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Clan.class)))
            })
        }
    )
    
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/onlinegame/calculate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<List<Clan>>> calculate(
        @Parameter(name = "Players", description = "", required = true) @Valid @RequestBody Players players
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
